### ISSUE TITLE
worker crashing on startup

### ISSUE THREAD

**Issue by jsnoble** [terascope/teraslice_kafka_sender#8]
If a job is started up while kafka is down, it provisions a slice to the worker but it sits there and waits. After a period of time the error below is thrown and the worker completely crashes losing any reference to the slice. The result of this is that the job is not marked as failing since there is no reply back. There should be improved error handling so that it throws regularly instead of completely crashing the worker

[2018-02-13T18:57:07.047Z] ERROR: teraslice/79515 on MacBook-Pro-3.local: Error connecting to Kafka: Error: broker transport failure
[2018-02-13T18:57:07.048Z] ERROR: teraslice/79515 on MacBook-Pro-3.local: Error in worker: 10 pid: 79515
[2018-02-13T18:57:07.048Z] ERROR: teraslice/79515 on MacBook-Pro-3.local: broker transport failure
[2018-02-13T18:57:07.048Z] ERROR: teraslice/79515 on MacBook-Pro-3.local:
    Error: Local: Broker transport failure
        at Function.createLibrdkafkaError [as create] (/Users/jarednoble/Projects/terascope/terafoundation_kafka_connector/node_modules/node-rdkafka/lib/error.js:260:10)
        at /Users/jarednoble/Projects/terascope/terafoundation_kafka_connector/node_modules/node-rdkafka/lib/client.js:337:28

**Comment by kstaken** [comment]
The delay here is the result of the timeout on flushing the data. It defaults to 60000ms which if a broker is unavailable would be the time it waits for it to become available. Other than maybe making the timeout configurable was there anything else you saw here that is a problem?
